"""
StockQueen V1 - Pharma Watchlist Configuration
"""

PHARMA_WATCHLIST = {
    # 小盘生物科技股（市值5-40亿，目标事件驱动策略）
    "SAVA": "Cassava Sciences",
    "ACAD": "ACADIA Pharmaceuticals",
    "HALO": "Halozyme Therapeutics",
    "KRTX": "Karuna Therapeutics",
    "ARQT": "Arcutis Biotherapeutics",
    "IMVT": "Immunovant",
    "KRYS": "Krystal Biotech",
    "RXRX": "Recursion Pharmaceuticals",
    "BEAM": "Beam Therapeutics",
    "EDIT": "Editas Medicine",
    "NTLA": "Intellia Therapeutics",
    "CRSP": "CRISPR Therapeutics",
    "PTCT": "PTC Therapeutics",
    "BLUE": "bluebird bio",
    "NBIX": "Neurocrine Biosciences",
    "SRPT": "Sarepta Therapeutics",
    "EXEL": "Exelixis",
    "INCY": "Incyte",
    "JAZZ": "Jazz Pharmaceuticals",
    "SGEN": "Seagen",
    # 新增小盘生物科技股
    "VKTX": "Viking Therapeutics",
    "ARWR": "Arrowhead Pharmaceuticals",
    "IONS": "Ionis Pharmaceuticals",
    "ALNY": "Alnylam Pharmaceuticals",
    "BMRN": "BioMarin Pharmaceutical",
    "RARE": "Ultragenyx Pharmaceutical",
    "IONS": "Ionis",
    "PCVX": "Vaxcyte",
    "MRNA": "Moderna",
    "NVAX": "Novavax",
    "BNTX": "BioNTech",
    "ADPT": "Adaptive Biotechnologies",
    "FATE": "Fate Therapeutics",
    "CARV": "Caribou Biosciences",
    "TWST": "Twist Bioscience",
    "GCT": "Ginkgo Bioworks",
    "DNA": "Ginkgo Bioworks",
    "ZYME": "Zymeworks",
    "ABSI": "Absci Corporation",
    "SDGR": "Schrödinger",
    "PRCT": "Procept Biorobotics",
    "AVTE": "Avtec Therapeutics",
    "CERE": "Cerevel Therapeutics",
    "XFOR": "X4 Pharmaceuticals",
    "AUTL": "Autolus Therapeutics",
    "TCRR": "Tcr2 Therapeutics",
    "ALLO": "Allogene",
    "RGNX": "Regenxbio",
    "KOD": "Kodiak Sciences",
    "VIR": "Vir Biotechnology",
    "ADAG": "Adagio Therapeutics",
    "MOR": "Morphic Therapeutic",
    # 中概医药
    "ZLAB": "再鼎医药",
    "BNR": "百奥赛图",
    "LEGN": "传奇生物",
    "BGNE": "百济神州",
    "CAN": "嘉林药业",
    # 美国医药（FDA敏感，大盘股）
    "PFE": "Pfizer",
    "MRK": "Merck",
    "JNJ": "Johnson & Johnson",
    "ABBV": "AbbVie",
    "BMY": "Bristol Myers Squibb",
    "LLY": "Eli Lilly",
    "AMGN": "Amgen",
    "GILD": "Gilead",
    "BIIB": "Biogen",
    "REGN": "Regeneron",
    "VRTX": "Vertex",
    "NVS": "Novartis",
    "AZN": "AstraZeneca",
    "SNY": "Sanofi",
    "GSK": "GSK",
    "TEVA": "Teva",
    "VTRS": "Viatris",
    "NVO": "Novo Nordisk",
}

PHARMA_KEYWORDS = {
    "Cassava": "SAVA",
    "ACADIA": "ACAD",
    "Halozyme": "HALO",
    "Karuna": "KRTX",
    "Arcutis": "ARQT",
    "Immunovant": "IMVT",
    "Krystal": "KRYS",
    "Recursion": "RXRX",
    "Beam Therapeutics": "BEAM",
    "Editas": "EDIT",
    "Intellia": "NTLA",
    "CRISPR Therapeutics": "CRSP",
    "PTC Therapeutics": "PTCT",
    "bluebird": "BLUE",
    "Neurocrine": "NBIX",
    "Sarepta": "SRPT",
    "Exelixis": "EXEL",
    "Incyte": "INCY",
    "Jazz": "JAZZ",
    "Seagen": "SGEN",
    "Viking": "VKTX",
    "Arrowhead": "ARWR",
    "Ionis": "IONS",
    "Alnylam": "ALNY",
    "BioMarin": "BMRN",
    "Ultragenyx": "RARE",
    "Vaxcyte": "PCVX",
    "Moderna": "MRNA",
    "Novavax": "NVAX",
    "BioNTech": "BNTX",
    "Adaptive": "ADPT",
    "Fate Therapeutics": "FATE",
    "Caribou": "CARV",
    "Twist Bioscience": "TWST",
    "Ginkgo": "GCT",
    "Zymeworks": "ZYME",
    "Absci": "ABSI",
    "Schrödinger": "SDGR",
    "Procept": "PRCT",
    "Cerevel": "CERE",
    "Vir Biotechnology": "VIR",
    "Regenxbio": "RGNX",
    "Kodiak": "KOD",
    "再鼎": "ZLAB",
    "百济": "BGNE",
    "BeiGene": "BGNE",
    "传奇": "LEGN",
    "Legend Biotech": "LEGN",
    "Pfizer": "PFE",
    "Eli Lilly": "LLY",
    "Ozempic": "NVO",
    "Wegovy": "NVO",
    "Keytruda": "MRK",
    "Humira": "ABBV",
    "Regeneron": "REGN",
    "Vertex": "VRTX",
    "Sanofi": "SNY",
    "Novo Nordisk": "NVO",
    "AstraZeneca": "AZN",
    "GSK": "GSK",
    "Roche": "RHHBY",
    "Novartis": "NVS",
    "Teva": "TEVA",
    "Viatris": "VTRS",
    "Bristol Myers": "BMY",
    "Johnson Johnson": "JNJ",
    "BIOGEN": "BIIB",
    "GILEAD": "GILD",
    "AMGEN": "AMGN",
}
