#!/usr/bin/env python3
"""
train_exit_scorer.py
────────────────────
Trains the ML Exit Scorer (Tranche B exit optimization) using the
data generated by generate_exit_scorer_data.py.

Model: XGBoost Classifier
Task:  Binary classification — should Tranche B exit now?
       label=1 → forward 3d return will erode profit (exit)
       label=0 → hold, profit likely to continue or stabilise

Output:
  models/exit_scorer/exit_scorer.pkl     (production model)
  models/exit_scorer/feature_names.json  (feature order for inference)
  models/exit_scorer/walk_forward_results.json  (validation metrics)

Usage:
  # Train on all data (quick check):
  python scripts/train_exit_scorer.py

  # Run full Walk-Forward validation:
  python scripts/train_exit_scorer.py --walk-forward

  # Adjust exit probability threshold:
  python scripts/train_exit_scorer.py --walk-forward --threshold 0.70
"""

import json
import pickle
import argparse
import sys
from pathlib import Path
from collections import defaultdict

import numpy as np
import pandas as pd

# ── Project root ──────────────────────────────────────────────────────────────
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

DATA_CSV    = ROOT / "scripts" / "exit_scorer_training_data.csv"
MODEL_DIR   = ROOT / "models" / "exit_scorer"
MODEL_PATH  = MODEL_DIR / "exit_scorer.pkl"
FEAT_PATH   = MODEL_DIR / "feature_names.json"
WF_PATH     = MODEL_DIR / "walk_forward_results.json"

# Features used for training (must match generate_exit_scorer_data.py output)
FEATURE_COLS = [
    "days_held",
    "unrealized_pnl_pct",
    "pnl_peak_pct",
    "pnl_drawdown_from_peak",   # ← most predictive
    "rsi_14",
    "price_vs_ma5_pct",
    "spy_3d_return_pct",
    "atr_ratio",
]

# Categorical encoding maps
REGIME_MAP   = {"bear": 0, "choppy": 1, "bull": 2, "strong_bull": 3}
CATEGORY_MAP = {"defensive": 0, "inverse": 1, "stock": 2}


# ── Feature engineering ───────────────────────────────────────────────────────

def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """Convert raw CSV columns → model feature matrix."""
    out = df[FEATURE_COLS].copy().astype(float)
    out["regime_code"]   = df["regime"].map(REGIME_MAP).fillna(1).astype(int)
    out["etf_type_code"] = df["etf_category"].map(CATEGORY_MAP).fillna(2).astype(int)
    return out


MIN_PROFIT_ACTIVATE = 0.5   # % — only train on rows where Tranche B would be active


def load_data() -> pd.DataFrame:
    if not DATA_CSV.exists():
        print(f"❌  Training data not found: {DATA_CSV}")
        print("    Run first:  python scripts/generate_exit_scorer_data.py")
        sys.exit(1)
    df = pd.read_csv(DATA_CSV)
    raw = len(df)

    # Filter to rows where Tranche B activation condition is met:
    # unrealized_pnl >= MIN_PROFIT_ACTIVATE%
    # This removes feature leakage (unrealized_pnl was a proxy for the label
    # because label=1 is only possible when unrealized_pnl >= 0.5%)
    df = df[df["unrealized_pnl_pct"] >= MIN_PROFIT_ACTIVATE].copy()

    print(f"✅  Loaded {raw:,} rows → filtered to {len(df):,} (unrealized_pnl >= {MIN_PROFIT_ACTIVATE}%)")
    print(f"    Label distribution: label=1 (exit) {df['label'].mean():.1%} | "
          f"label=0 (hold) {1 - df['label'].mean():.1%}")
    return df


# ── Model training ────────────────────────────────────────────────────────────

def train_model(X: pd.DataFrame, y: pd.Series, scale_pos: float = None):
    """Train XGBoost binary classifier."""
    try:
        from xgboost import XGBClassifier
    except ImportError:
        print("❌  xgboost not installed. Run: pip install xgboost")
        sys.exit(1)

    # Auto-balance classes if not specified
    if scale_pos is None:
        n_neg = (y == 0).sum()
        n_pos = (y == 1).sum()
        scale_pos = n_neg / n_pos if n_pos > 0 else 1.0

    model = XGBClassifier(
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_pos,   # handles class imbalance
        use_label_encoder=False,
        eval_metric="logloss",
        random_state=42,
        verbosity=0,
    )
    model.fit(X, y)
    return model


def evaluate(model, X: pd.DataFrame, y: pd.Series, threshold: float = 0.65) -> dict:
    """Evaluate model at given exit probability threshold."""
    proba  = model.predict_proba(X)[:, 1]
    preds  = (proba >= threshold).astype(int)

    tp = int(((preds == 1) & (y == 1)).sum())
    fp = int(((preds == 1) & (y == 0)).sum())
    tn = int(((preds == 0) & (y == 0)).sum())
    fn = int(((preds == 0) & (y == 1)).sum())

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1        = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    accuracy  = (tp + tn) / len(y)

    return {
        "threshold": threshold,
        "precision": round(precision, 4),
        "recall":    round(recall, 4),
        "f1":        round(f1, 4),
        "accuracy":  round(accuracy, 4),
        "tp": tp, "fp": fp, "tn": tn, "fn": fn,
        "n_samples": len(y),
        "exit_signal_rate": round((preds == 1).mean(), 4),
    }


# ── Walk-Forward Validation ───────────────────────────────────────────────────

def walk_forward_validate(df: pd.DataFrame, threshold: float = 0.65) -> list:
    """
    Expanding-window Walk-Forward validation.
    Mirrors the ML Ranker's validation approach.

    Windows (train → test):
      W1: 2022-01 ~ 2023-06  →  2023-07 ~ 2023-12
      W2: 2022-01 ~ 2023-12  →  2024-01 ~ 2024-06
      W3: 2022-01 ~ 2024-06  →  2024-07 ~ 2024-12
      W4: 2022-01 ~ 2024-12  →  2025-01 ~ 2025-06
      W5: 2022-01 ~ 2025-06  →  2025-07 ~ 2026-03
    """
    df = df.copy()
    df["date"] = pd.to_datetime(df["date"])

    windows = [
        ("W1", "2023-07-01", "2024-01-01"),
        ("W2", "2024-01-01", "2024-07-01"),
        ("W3", "2024-07-01", "2025-01-01"),
        ("W4", "2025-01-01", "2025-07-01"),
        ("W5", "2025-07-01", "2026-04-01"),
    ]

    results = []
    print("\n─── Walk-Forward Validation ─────────────────────────────────")
    print(f"{'Window':<6} {'Train':<12} {'Test':<12} {'Precision':>10} {'Recall':>8} {'F1':>8} {'ExitRate':>10}")
    print("─" * 62)

    for name, test_start, test_end in windows:
        test_start_ts = pd.Timestamp(test_start)
        test_end_ts   = pd.Timestamp(test_end)

        train_df = df[df["date"] < test_start_ts]
        test_df  = df[(df["date"] >= test_start_ts) & (df["date"] < test_end_ts)]

        if len(train_df) < 500 or len(test_df) < 100:
            print(f"{name:<6} insufficient data (train={len(train_df)}, test={len(test_df)})")
            continue

        X_train = build_features(train_df)
        y_train = train_df["label"]
        X_test  = build_features(test_df)
        y_test  = test_df["label"]

        model  = train_model(X_train, y_train)
        metrics = evaluate(model, X_test, y_test, threshold)
        metrics["window"]      = name
        metrics["train_rows"]  = len(train_df)
        metrics["test_rows"]   = len(test_df)
        metrics["train_start"] = "2022-01-01"
        metrics["train_end"]   = test_start
        metrics["test_start"]  = test_start
        metrics["test_end"]    = test_end

        results.append(metrics)
        print(f"{name:<6} 2022-01~{test_start[:7]:<9} {test_start[:7]}~{test_end[:7]:<9} "
              f"{metrics['precision']:>10.3f} {metrics['recall']:>8.3f} "
              f"{metrics['f1']:>8.3f} {metrics['exit_signal_rate']:>10.3f}")

    if results:
        avg_p  = np.mean([r["precision"] for r in results])
        avg_r  = np.mean([r["recall"]    for r in results])
        avg_f1 = np.mean([r["f1"]        for r in results])
        avg_er = np.mean([r["exit_signal_rate"] for r in results])
        print("─" * 62)
        print(f"{'AVG':<6} {'':^21} {avg_p:>10.3f} {avg_r:>8.3f} {avg_f1:>8.3f} {avg_er:>10.3f}")

        # Verdict
        print(f"""
Verdict:
  Precision {avg_p:.3f} = when Exit Scorer says "出场"，{avg_p:.1%} of the time it's right
  Recall    {avg_r:.3f} = catches {avg_r:.1%} of actual profit-erosion events
  F1        {avg_f1:.3f} = combined score (target ≥ 0.50 to deploy)
  Exit Rate {avg_er:.1%} = {avg_er:.1%} of held positions get early exit signal
""")

        if avg_f1 >= 0.50:
            print("✅  Model meets deployment threshold (F1 ≥ 0.50). Safe to deploy Tranche B.")
        else:
            print("⚠️   F1 < 0.50. Consider adjusting threshold or gathering more data.")

    return results


# ── Feature importance ────────────────────────────────────────────────────────

def print_feature_importance(model, feature_names: list) -> None:
    importances = model.feature_importances_
    ranked = sorted(zip(feature_names, importances), key=lambda x: x[1], reverse=True)
    print("\nFeature Importance:")
    for feat, imp in ranked:
        bar = "█" * int(imp * 40)
        print(f"  {feat:<30} {imp:.4f}  {bar}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Train ML Exit Scorer")
    parser.add_argument("--walk-forward", action="store_true",
                        help="Run Walk-Forward validation before final training")
    parser.add_argument("--threshold", type=float, default=0.65,
                        help="Exit probability threshold (default: 0.65)")
    args = parser.parse_args()

    df = load_data()

    # ── Walk-Forward validation ──
    wf_results = []
    if args.walk_forward:
        wf_results = walk_forward_validate(df, threshold=args.threshold)

    # ── Full-data training (production model) ──
    print("\n─── Training production model on full dataset ───────────────")
    X_all = build_features(df)
    y_all = df["label"]
    all_feature_names = list(X_all.columns)

    model = train_model(X_all, y_all)

    # In-sample eval (sanity check only)
    in_sample = evaluate(model, X_all, y_all, threshold=args.threshold)
    print(f"In-sample (threshold={args.threshold}):")
    print(f"  Precision={in_sample['precision']:.3f}  Recall={in_sample['recall']:.3f}  "
          f"F1={in_sample['f1']:.3f}  ExitRate={in_sample['exit_signal_rate']:.1%}")

    print_feature_importance(model, all_feature_names)

    # ── Save model ──
    MODEL_DIR.mkdir(parents=True, exist_ok=True)

    with open(MODEL_PATH, "wb") as f:
        pickle.dump(model, f)
    print(f"\n✅  Model saved → {MODEL_PATH}")

    with open(FEAT_PATH, "w", encoding="utf-8") as f:
        json.dump(all_feature_names, f, indent=2)
    print(f"✅  Feature names → {FEAT_PATH}")

    if wf_results:
        with open(WF_PATH, "w", encoding="utf-8") as f:
            json.dump({
                "threshold":   args.threshold,
                "feature_cols": all_feature_names,
                "windows":     wf_results,
                "avg_precision": round(float(np.mean([r["precision"] for r in wf_results])), 4),
                "avg_recall":    round(float(np.mean([r["recall"] for r in wf_results])), 4),
                "avg_f1":        round(float(np.mean([r["f1"] for r in wf_results])), 4),
            }, f, indent=2)
        print(f"✅  Walk-Forward results → {WF_PATH}")


if __name__ == "__main__":
    main()
